pipeline{
	agent any
	stages{
		
		stage("test"){
			steps{
			nodejs(nodeJSInstallationName:'nodejs'){	
			   sh "npm install"	
			}	
			}
			
			
			
		}
 		stage("sonarqube analysis"){
 			steps{
				nodejs(nodeJSInstallationName:'nodejs'){
 					sh "npm install"
					withSonarQubeEnv("SonarQube Scanner"){
						 println ${env.SONAR_HOST_URL} 
 						sh "npm install sonar-scanner"
 					}
				}
 			}
 		}
	}
}
