pipeline{
	agent any
	stages{
		stage("sonarqube analysis"){
			steps{
				nodejs(nodeJSInstallationName:'nodejs'){
					sh "npm install"
					withSonarQubeEnv("test-npm"){
						sh "npm install sonar-scanner"
					}
				}
			}
		}
	}
}
