pipeline{
	agent any
	stages{
		
		stage("test"){
			steps{
			nodejs(nodeJSInstallationName:'nodejs'){	
			   sh "npm install"	
			}	
			}
			
			
			
		}
 		stage("sonarqube analysis"){
 			steps{
// 				nodejs(nodeJSInstallationName:'nodejs'){
//  					sh "npm install"
// 					withSonarQubeEnv("SonarQube Scanner"){
// 						// println ${env.SONAR_HOST_URL} 
//  						sh "npm install sonar-scanner"
//  					}
// 				}
				stage('SonarQube analysis') {
				
				    def scannerHome = tool 'SonarScanner 4.0';
				    withSonarQubeEnv('SonarQube Scanner') { // If you have configured more than one global server connection, you can specify its name
				      sh "${scannerHome}/bin/sonar-scanner"
				    }
					
				  }
 			}
 		}
	}
}
